[project]
name = "mcp-server"
version = "0.1.0"
description = "Expense Tracker MCP"
readme = "README.md"
requires-python = ">=3.12,<3.13"

dependencies = [
    "fastmcp",
    "psycopg[binary]",   # VERY IMPORTANT
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
