[project]
name = "mcp-server"
version = "0.1.0"
description = "MCP Server using PostgreSQL"
requires-python = ">=3.12,<3.13"

dependencies = [
    "fastmcp>=2.13.0",
    "psycopg>=3.1.12",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

